name: Publish Editor

on:
    workflow_dispatch:
    release:
        types: [published]

permissions:
    contents: read

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: latest
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: npm install

            - name: Publish editor
              run: npm run editor:publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
